server:
  port: 8080

spring:
  application:
    name: keycloakCN
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DB_VENDOR:mysql}://${DB_ADDR:127.0.0.1}:${MYSQL_PORT:3306}/${DB_DATABASE:keycloak}?useunicode=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: ${DB_USER:keycloak}
    password: ${DB_PASSWORD:keycloak}
    druid:
      # 连接池配置
      filters: stat,slf4j
      initial-size: 1
      max-active: 20
      min-idle: 8

      #监控配置
      web-stat-filter:
        enabled: true
  devtools:
    restart:
      enabled: true

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: ${KEYCLOAK_USER:admin}
      password: ${KEYCLOAK_PASSWORD:admin}
    realmImportFile: import-realm.json