server:
  port: 8080

spring:
  application:
    name: bslcloud-keycloak
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9d8u75j300675v7lo.mysql.rds.aliyuncs.com:3306/keycloak?useunicode=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: dev_hql
    password: gnzSYtY4$QPF#2!8
    druid:
      # 连接池配置
      filters: stat,slf4j
      initial-size: 1
      max-active: 20
      min-idle: 8

      #监控配置
      web-stat-filter:
        enabled: true
  devtools:
    restart:
      enabled: true

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: import-realm.json